// Source: https://www.mydogsname.com/funny-dog-quotes/
const quotes = [
  'A dog can express more with his tail in minutes than his owner can express with his tongue in hours.',
  'Beware! Dog can’t hold its licker.',
  'Choosing a dog may be the only chance you get to pick a relative.',
  'Dogs are like potato chips. You can’t have just one.',
  'Dogs are my favorite people.',
  'Dogs over dudes.',
  'Every snack you make, every meal you bake, every bite you take…I’ll be watching you.',
  'Handle every situation like a dog. If you can’t eat it or play with it, just pee on it and walk away.',
  'I am one dog short of crazy.',
  'I don’t care who dies in the movie, as long as the dog lives.',
  'I feel sorry for people who don’t have dogs. I hear they have to pick up food they drop on the floor.',
  'I work hard so my dog can have a better life.',
  'If aliens saw us walking our dogs and picking up their poop, who would they think is in charge?',
  'If our dog doesn’t like you, we probably won’t either.',
  'If you want the best seat in the house, you’ll have to move the dog.',
  'If you’re uncomfortable around my dog, I’m happy to lock you in the other room when you come over.',
  'If you’re uncomfortable around my dog, I’m happy to lock you in the other room when you come over.',
  'If your dog is fat, you aren’t getting enough exercise.',
  'It’s OK if you don’t like my dog, not everyone has good taste.',
  'Leave me only – I’m only speaking to dogs today.',
  'Less people, more dogs.',
  'Life without a dog is like an unsharpened pencil. It has no point.',
  'No home decor is complete without dog hair.',
  'Nothing in the world is friendlier than a wet dog.',
  'Some days you’re the dog; some days you’re the hydrant.',
  'The best therapist has fur and four legs.',
  'The more people I meet, the more I love my dog.',
  'The only person who understands me is my dog.',
  'The reason a dog has so many friends is that he wags his tail instead of his tongue.',
  'This home is filled with love and dog hair.',
  'To err is human — to forgive, canine.',
  'When I die my dog gets everything.',
  'Whoever said you can’t buy happiness forgot about puppies.',
  'Without my dog my wallet would be full my house would be clean but my heart would be empty.',
  'You can trust your dog to guard your house but never trust your dog to guard your sandwich.',
]

quotes.sort(() => 0.5 - Math.random())

export default quotes
